Ctrl+c quit


q   playlist-prev
e   playlist-next
w   add volume 5

s   add volume -5
a   seek -5
d   seek 5

z   add speed -0.1
x   add speed 0.1

c   cycle sub
r   cycle-values loop-file "inf" "no"
f   cycle fullscreen

Ctrl+a   frame-back-step
Ctrl+d   frame-step

Ctrl+z    add speed -0.25
Ctrl+x    add speed  0.25

Shift+z   add speed -0.1
Shift+x   add speed  0.1

Alt+z     add speed -0.01
Alt+x     add speed  0.01

v       set speed 1.0
