$primary             = rgb(ffb86b)
$on_primary          = rgb(492900)
$primary_container   = rgb(683d00)
$secondary           = rgb(e6c18d)
$background          = rgb(1c1107)
$on_background       = rgb(f5dfcc)
$surface             = rgb(1c1107)
$surface_variant     = rgb(524436)
$on_surface_variant  = rgb(d8c3b1)
$outline             = rgb(a08d7d)
$error               = rgb(ffb4ab)
