$primary             = rgb(acd600)
$on_primary          = rgb(293500)
$primary_container   = rgb(3c4d00)
$secondary           = rgb(b7cea2)
$background          = rgb(121509)
$on_background       = rgb(e2e4d0)
$surface             = rgb(121509)
$surface_variant     = rgb(454839)
$on_surface_variant  = rgb(c6c8b4)
$outline             = rgb(909280)
$error               = rgb(ffb4ab)
