$primary             = rgb(c2d000)
$on_primary          = rgb(2f3300)
$primary_container   = rgb(454b00)
$secondary           = rgb(bdcd9c)
$background          = rgb(131408)
$on_background       = rgb(e5e4ce)
$surface             = rgb(131408)
$surface_variant     = rgb(474838)
$on_surface_variant  = rgb(c8c8b2)
$outline             = rgb(92927f)
$error               = rgb(ffb4ab)
