foreground              #e2e2e2
background              #131313
selection_foreground    #1b1b1b
selection_background    #ffffff
cursor                  #ffffff
cursor_text_color       #1b1b1b
url_color               #e2e2e2

# Black
color0  #131313
color8  #474747
# Red
color1  #ffb4ab
color9  #ffb4ab
# Green
color2  #e2e2e2
color10 #e2e2e2
# Yellow
color3  #c6c6c6
color11 #474747
# Blue
color4  #ffffff
color12 #d4d4d4
# Magenta
color5  #000000
color13 #000000
# Cyan
color6  #000000
color14 #000000
# White
color7  #e2e2e2
color15 #e2e2e2
