foreground              #e3e1ef
background              #12131c
selection_foreground    #0000ac
selection_background    #bfc2ff
cursor                  #bfc2ff
cursor_text_color       #0000ac
url_color               #dbbaf1

# Black
color0  #12131c
color8  #464651
# Red
color1  #ffb4ab
color9  #ffb4ab
# Green
color2  #dbbaf1
color10 #dbbaf1
# Yellow
color3  #ccc1e9
color11 #4a4263
# Blue
color4  #bfc2ff
color12 #0200ef
# Magenta
color5  #e0e0ff
color13 #e0e0ff
# Cyan
color6  #f2daff
color14 #f2daff
# White
color7  #e3e1ef
color15 #e3e1ef
