foreground              #e6e2d5
background              #14140c
selection_foreground    #343200
selection_background    #ceca75
cursor                  #ceca75
cursor_text_color       #343200
url_color               #a5d0bb

# Black
color0  #14140c
color8  #49473a
# Red
color1  #ffb4ab
color9  #ffb4ab
# Green
color2  #a5d0bb
color10 #a5d0bb
# Yellow
color3  #cbc8a4
color11 #49482c
# Blue
color4  #ceca75
color12 #4b4900
# Magenta
color5  #ebe68e
color13 #ebe68e
# Cyan
color6  #c0ecd7
color14 #c0ecd7
# White
color7  #e6e2d5
color15 #e6e2d5
